import type { NextPage } from "next";
import Head from "next/head";
import { Transition } from "react-transition-group";
import AuthProvider from "../context/authContext";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthProvider>
        <main>Welcopm</main>
        <footer></footer>
      </AuthProvider>
    </div>
  );
};

export default Home;
